#common controlls
name: nova-customer-api
environment: test
containerPort: 80
registry: harborprdap01.anadoluhayat.com.tr

#deployment controlls

replicas: 1
resource:
 requests:
    cpu: 100m
    memory: 300Mi
 limits:
    cpu: 800m
    memory: 1200Mi

image:
 name: novacustomerapi
 imagePullSecret: harbor
 pullPolicy: Always
 test:
   repository: test
   tag: latest
 uat:
   repository: uat
   tag: latest
 prod:
   repository: prod
   tag: latest

envVar:
  configmap:
    test:
      ASPNETCORE_ENVIRONMENT: Development
    uat:
      ASPNETCORE_ENVIRONMENT: Development
    prod:
      ASPNETCORE_ENVIRONMENT: Production
  secret:
    test:
      InsisConnectionString: xxx
    uat:
      InsisConnectionString: xxx
    prod:
      InsisConnectionString: xxx


#Service Controllers

service:
  port: 80
  targetPort: 80
  type: ClusterIP

